name: build
on: 
  push:
    branches:
      - '*'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Java 21
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: 21
    - name: Build project
      run: mvn -B -ntp install
  jms:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Java 21
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: 21
    - name: Build project
      run: mvn -B -ntp install
    - name: Run tests
      run: |
        curl -O -L https://download.eclipse.org/ee4j/glassfish/glassfish-7.0.9.zip
        unzip glassfish-7.0.9.zip
        cd glassfish7/bin
        ./asadmin start-domain
        ./asadmin create-jms-resource --restype jakarta.jms.Queue --property Name=colibri jms/colibri
        cd ../../jms
        mvn -P glassfish verify
